package edu.unimetproyecto2.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import edu.unimetproyecto2.modelo.DiscoVirtual;
import javax.swing.JLabel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import edu.unimetproyecto2.modelo.Directorio;
import edu.unimetproyecto2.modelo.Archivo;
import edu.unimetproyecto2.modelo.Entrada;

/**
 *
 * @author jesus alejandro
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    // Atributos de la lógica (Fase 1)
    private DiscoVirtual disco; 
    private JLabel[] visualBloques; // Un arreglo para guardar los cuadritos y poder cambiarlos luego
    // Atributos del Árbol
    private Directorio rootLogico;       // La carpeta raíz real (Lógica)
    private DefaultTreeModel modeloArbol; // El motor que dibuja el árbol (Visual)

    public VentanaPrincipal() {
        initComponents(); // ¡No borrar esto!
        
        // Inicializamos nuestro disco de la Fase 1 (ejemplo: 100 bloques)
        disco = new DiscoVirtual(100); 
        visualBloques = new JLabel[100];
        
        // Llamamos al método que dibujará todo
        inicializarPanelDisco();
        
        // 1. Creamos la carpeta Raíz de la Fase 1
        rootLogico = new Directorio("Root", "Admin", null);

        // 2. Creamos el "Nodo Visual" que el JTree entiende
        DefaultMutableTreeNode nodoRaizVisual = new DefaultMutableTreeNode(rootLogico.getNombre());

        // 3. Creamos el modelo usando ese nodo
        modeloArbol = new DefaultTreeModel(nodoRaizVisual);

        // 4. Le decimos al componente JTree que use este modelo
        treeArchivos.setModel(modeloArbol);
        
        // Opcional: Prueba rápida para ver si funciona
        Archivo prueba = new Archivo("HolaMundo.txt", "Admin", 1, 0, java.awt.Color.BLUE, rootLogico);
        rootLogico.getHijos().insertar(prueba); // Usamos tu lista enlazada
        
        actualizarArbol(); // Método que haremos ahora
    }
    
    private void inicializarPanelDisco() {
        // 1. Limpiar el panel por si acaso
        panelDisco.removeAll(); 

        // 2. Usar un bucle para crear cada bloque visual
        for (int i = 0; i < disco.getTamanoTotal(); i++) {
            // Creamos un JLabel que servirá como "cuadrito"
            JLabel cuadro = new JLabel(String.valueOf(i), javax.swing.SwingConstants.CENTER);

            // Configuración visual del cuadrito
            cuadro.setOpaque(true); // Necesario para que se vea el color de fondo
            cuadro.setBackground(java.awt.Color.WHITE); // Blanco = Libre
            cuadro.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
            cuadro.setFont(new java.awt.Font("Segoe UI", 0, 9)); // Letra pequeña para el número

            // Guardamos la referencia en nuestro arreglo para usarla después
            visualBloques[i] = cuadro;

            // 3. Añadir el cuadrito al panel que dibujamos en la interfaz
            panelDisco.add(cuadro);
        }

        // 4. Refrescar la interfaz para que aparezcan
        panelDisco.revalidate();
        panelDisco.repaint();
    }
    
    private void actualizarArbol() {
        // Creamos el nodo raíz visual de nuevo para refrescar todo
        DefaultMutableTreeNode visualRoot = new DefaultMutableTreeNode(rootLogico.getNombre());
        
        // Llamamos a una función que recorra los hijos
        llenarNodos(visualRoot, rootLogico);
        
        // Le pasamos el nuevo diseño al modelo
        modeloArbol.setRoot(visualRoot);
        modeloArbol.reload(); // Obliga al JTree a redibujarse
    }

    private void llenarNodos(DefaultMutableTreeNode nodoVisual, Directorio directorioLogico) {
        // Recorremos la ListaEnlazada de hijos
        for (int i = 0; i < directorioLogico.getHijos().getTamano(); i++) {
            Entrada hijo = directorioLogico.getHijos().obtener(i);
            
            // Creamos el nodo para este hijo
            DefaultMutableTreeNode nuevoNodoVisual = new DefaultMutableTreeNode(hijo.getNombre());
            nodoVisual.add(nuevoNodoVisual);
            
            // Si ese hijo es una carpeta, tenemos que entrar y ver qué tiene dentro
            if (hijo.isEsDirectorio()) {
                llenarNodos(nuevoNodoVisual, (Directorio) hijo);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeArchivos = new javax.swing.JTree();
        panelDisco = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnFallo = new javax.swing.JButton();
        btnModo = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(treeArchivos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.WEST);

        panelDisco.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulación de Disco Virtual (SD)"));
        panelDisco.setLayout(new java.awt.GridLayout(10, 10, 2, 2));
        getContentPane().add(panelDisco, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("TABLA DE ASIGNACIÓN");
        jPanel1.add(jLabel1);

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Archivo", "Cant. Bloques", "Bloque Inicial", "Color"
            }
        ));
        jScrollPane2.setViewportView(tablaArchivos);

        jPanel1.add(jScrollPane2);

        jLabel2.setText("COLA DE PROCESOS");
        jPanel1.add(jLabel2);

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Operación", "Estado", "Bloque Obj."
            }
        ));
        jScrollPane3.setViewportView(tablaProcesos);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnCrear.setText("Crear Archivo");
        btnCrear.addActionListener(this::btnCrearActionPerformed);
        jPanel3.add(btnCrear);

        btnEliminar.setText("Eliminar");
        jPanel3.add(btnEliminar);

        btnFallo.setText("Simular Fallo");
        jPanel3.add(btnFallo);

        btnModo.setText("Cambiar Modo (Admin/User)");
        jPanel3.add(btnModo);

        btnConfig.setText("Configurar Disco");
        jPanel3.add(btnConfig);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setLineWrap(true);
        txtLog.setRows(5);
        jScrollPane4.setViewportView(txtLog);

        jPanel2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            // 1. Pedir datos al usuario (Ventanas simples)
            String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre del archivo:");
            String tamStr = javax.swing.JOptionPane.showInputDialog(this, "Tamaño (en bloques):");

            if (nombre == null || tamStr == null) return; // Si cancela, no hacemos nada
            int tamano = Integer.parseInt(tamStr);

            // 2. Buscar y asignar bloques (Asignación Encadenada)
            int bloqueAnterior = -1;
            int primerBloque = -1;
            java.awt.Color colorAzar = new java.awt.Color((int)(Math.random() * 0x1000000));

            // Verificamos si hay espacio suficiente antes de empezar
            // (Podrías hacer un método en DiscoVirtual para contar libres)

            for (int i = 0; i < tamano; i++) {
                int libre = disco.buscarBloqueLibre();
                if (libre == -1) {
                    txtLog.append("Error: No hay suficiente espacio en disco.\n");
                    return;
                }

                // Ocupamos el bloque en la lógica
                edu.unimetproyecto2.modelo.Bloque b = disco.getBloque(libre);
                b.setOcupado(true);
                b.setNombreArchivo(nombre);
                b.setColorArchivo(colorAzar);

                // Encadenamiento
                if (bloqueAnterior != -1) {
                    disco.getBloque(bloqueAnterior).setSiguienteBloque(libre);
                } else {
                    primerBloque = libre; // Guardamos el inicio del archivo
                }
                bloqueAnterior = libre;

                // 3. Actualizar Visualmente el cuadrito en el panel central
                visualBloques[libre].setBackground(colorAzar);
                visualBloques[libre].setToolTipText("Archivo: " + nombre);
            }

            // 4. Crear el objeto Archivo y añadirlo al sistema
            edu.unimetproyecto2.modelo.Archivo nuevo = new edu.unimetproyecto2.modelo.Archivo(
                    nombre, "Admin", tamano, primerBloque, colorAzar, rootLogico);

            rootLogico.getHijos().insertar(nuevo);

            // 5. Refrescar el JTree y el Log
            actualizarArbol();
            txtLog.append("Archivo '" + nombre + "' creado con éxito (" + tamano + " bloques).\n");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El tamaño debe ser un número.");
          }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
        VentanaPrincipal vista = new VentanaPrincipal();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null); // Esto la centra en la pantalla
        });
        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFallo;
    private javax.swing.JButton btnModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelDisco;
    private javax.swing.JTable tablaArchivos;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JTree treeArchivos;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
